name: 'API'

on:
  push:
    branches: [main]
    paths: ['backend-api/**', '.github/**']
  pull_request:
    branches: [main]
    paths: ['backend-api/**', '.github/**']
  workflow_dispatch:

defaults:
  run:
    working-directory: backend-api
    
jobs:

  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 12.0
      uses: actions/setup-node@v1
      with:
        node-version: 12.0

    - run: npm install
    - run: npm run build --if-present

  dev:  
    name: 'Deploy Dev'
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: dev      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.0
      uses: actions/setup-node@v1
      with:
        node-version: 12.0

    - run: npm install
    - run: npm run build --if-present
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
        
    - name: 'Deploy'
      uses: azure/webapps-deploy@v2
      with:
        app-name: auth0appdemo-dev-api
        package: backend-api

  staging:  
    name: 'Deploy Staging'
    runs-on: ubuntu-latest
    needs: dev
    environment: 
      name: staging      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.0
      uses: actions/setup-node@v1
      with:
        node-version: 12.0

    - run: npm install
    - run: npm run build --if-present
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_STAGING }}
        
    - name: 'Deploy'
      uses: azure/webapps-deploy@v2
      with:
        app-name: auth0appdemo-staging-api
        package: backend-api

  prod:  
    name: 'Deploy Prod'
    runs-on: ubuntu-latest
    environment: 
      name: staging      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.0
      uses: actions/setup-node@v1
      with:
        node-version: 12.0

    - run: npm install
    - run: npm run build --if-present
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}
        
    - name: 'Deploy'
      uses: azure/webapps-deploy@v2
      with:
        app-name: auth0appdemo-prod-api
        package: backend-api