name: 'App'

on:
  push:
    branches: [main]
    paths: ['frontend-app/**', '.github/**']
  pull_request:
    branches: [main]
    paths: ['frontend-app/**', '.github/**']
  workflow_dispatch:
  
defaults:
  run:
    working-directory: frontend-app
    
jobs:

  build:
    env: 
      REACT_APP_AUTH_CONFIG_DOMAIN: ${{ secrets.AUTH0_DOMAIN_DEV }}
      REACT_APP_AUTH_CONFIG_CLIENTID: ${{ secrets.AUTH0_CLIENTID_DEV }}
      REACT_APP_AUTH_CONFIG_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE_DEV }}
      REACT_APP_API_ORIGIN: ${{ secrets.API_ORIGIN_DEV }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 12.0
      uses: actions/setup-node@v1
      with:
        node-version: 12.0

    - run: npm install
    - run: npm run build --if-present
    - run: npm run test
      env:
        CI: true
        
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
    
    - name: 'Deploy'
      uses: azure/webapps-deploy@v2
      with:
        app-name: auth0appdemo-dev-app
        package: ./frontend-app/build
      env:
        CI: true


